sudo: required
services:
  - docker

before_install:
  - docker build -t ashok/docker-react -f Dockerfile.dev .

  
script:
# Following command is failing so commenting it for now
#- docker run -e CI=true ashok/docker-react npm run test

# just run the image in container and and execute date command, hopefully it should return 0 and travis build will be successful
  - docker run ashok/docker-react date